generatorName: typescript-fetch
globalProperties:
  apiDocs: false
  apiTests: false
  modelDocs: false
  modelTests: false
additionalProperties:
  supportsES6: true
  typescriptThreePlus: true
  useSingleRequestParameter: true
  withInterfaces: true
